# fly.toml app configuration file generated for linmso-backend on 2025-10-31T20:08:01-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'linmso-backend'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
